"""Inicial

Revision ID: 33cc07279848
Revises: 
Create Date: 2025-11-10 22:58:32.076927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cc07279848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
